package cli

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/spf13/cobra"

	"github.com/raiyanyahya/llmaker/internal/backend"
)

// `build` is the advanced escape hatch from the plan (§4): the 95% path runs
// prebuilt images, but when config genuinely can't express what you need —
// a custom base, a CPU-tuned compile, a model baked into the image — this
// generates a Dockerfile build context you can customize and `docker build`.
func newBuildCmd(app *App) *cobra.Command {
	var (
		backendName string
		base        string
		model       string
		output      string
		printOnly   bool
	)
	cmd := &cobra.Command{
		Use:     "build",
		Short:   "Generate a custom image build context (advanced)",
		GroupID: groupAdvanced,
		Args:    cobra.NoArgs,
		Long: `Generate a Dockerfile build context for a custom llmaker image. This is the
escape hatch for cases the prebuilt images can't cover. Edit the generated files,
then build with: docker build -t my-llmaker ./<output>`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runBuild(cmd.Context(), app, buildOptions{
				backendName: backendName, base: base, model: model,
				output: output, printOnly: printOnly,
			})
		},
	}
	cmd.Flags().StringVar(&backendName, "backend", "ollama", "backend to scaffold (ollama, llamacpp)")
	cmd.Flags().StringVar(&base, "base", "", "override the base image")
	cmd.Flags().StringVar(&model, "model", "", "bake a model into the image (ollama only)")
	cmd.Flags().StringVarP(&output, "output", "o", "llmaker-build", "output directory for the build context")
	cmd.Flags().BoolVar(&printOnly, "print", false, "print the Dockerfile to stdout instead of writing files")
	return cmd
}

type buildOptions struct {
	backendName string
	base        string
	model       string
	output      string
	printOnly   bool
}

type dockerfileData struct {
	Base    string
	Backend string
	Model   string
}

func runBuild(_ context.Context, app *App, opts buildOptions) error {
	b, err := backend.Get(opts.backendName)
	if err != nil {
		return err
	}
	base := firstNonEmpty(opts.base, defaultBase(b.Kind))

	dockerfile, err := render(dockerfileTemplate, dockerfileData{
		Base:    base,
		Backend: string(b.Kind),
		Model:   opts.model,
	})
	if err != nil {
		return err
	}

	io := app.IO
	t := io.Theme

	if opts.printOnly {
		io.Printf("%s", dockerfile)
		return nil
	}

	if err := os.MkdirAll(opts.output, 0o755); err != nil {
		return err
	}
	files := map[string]string{
		"Dockerfile":    dockerfile,
		"entrypoint.sh": entrypointTemplate,
		"README.md":     fmt.Sprintf(buildReadme, opts.backendName, opts.output),
	}
	for name, content := range files {
		path := filepath.Join(opts.output, name)
		mode := os.FileMode(0o644)
		if name == "entrypoint.sh" {
			mode = 0o755
		}
		if err := os.WriteFile(path, []byte(content), mode); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}

	io.Println(t.SuccessLine("Generated build context in " + t.Accent.Render(opts.output+"/")))
	io.Println(t.Muted.Render("Customize the files, then build:"))
	io.Println("  " + t.Accent.Render(fmt.Sprintf("docker build -t my-llmaker-%s %s", opts.backendName, opts.output)))
	io.Println("  " + t.Accent.Render(fmt.Sprintf("llmaker up --image my-llmaker-%s", opts.backendName)))
	return nil
}

func defaultBase(k backend.Kind) string {
	switch k {
	case backend.LlamaCPP:
		return "ghcr.io/ggml-org/llama.cpp:server"
	default:
		return "ollama/ollama:latest"
	}
}

func render(tmpl string, data any) (string, error) {
	tt, err := template.New("dockerfile").Parse(tmpl)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tt.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

const dockerfileTemplate = `# Generated by ` + "`llmaker build`" + ` — customize as needed.
# Build context expects the llmaker facade at ./facade (copy it from the repo,
# or replace the COPY below with: pip install llmaker-facade once published).
FROM {{.Base}}

ENV LLMAKER_BACKEND={{.Backend}} \
    FACADE_PORT=8080 \
    PYTHONUNBUFFERED=1

# Install the Python control-plane facade and its dependencies.
RUN (command -v python3 >/dev/null 2>&1 || (apt-get update && apt-get install -y --no-install-recommends python3 python3-pip && rm -rf /var/lib/apt/lists/*))
COPY facade/ /opt/llmaker-facade/
RUN python3 -m pip install --no-cache-dir /opt/llmaker-facade
{{if .Model}}
# Bake the model into the image for a fully self-contained server.
RUN ollama serve & sleep 3 && ollama pull {{.Model}} && pkill ollama || true
{{end}}
COPY entrypoint.sh /usr/local/bin/llmaker-entrypoint
RUN chmod +x /usr/local/bin/llmaker-entrypoint

EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/llmaker-entrypoint"]
`

const entrypointTemplate = `#!/usr/bin/env bash
# Generated by llmaker build. Starts the backend then the facade.
set -euo pipefail

# Start the backend engine in the background (Ollama example).
if command -v ollama >/dev/null 2>&1; then
  ollama serve &
fi

# Hand off to the facade, which serves the OpenAI-compatible API + web UI.
exec python3 -m uvicorn app.main:app --host 0.0.0.0 --port "${FACADE_PORT:-8080}"
`

const buildReadme = `# Custom llmaker image (%s)

This directory was generated by ` + "`llmaker build`" + `.

1. Copy the facade source here:  cp -r /path/to/llmaker/facade ./facade
2. Edit the Dockerfile/entrypoint as needed.
3. Build:  docker build -t my-llmaker ./%s
4. Run:    llmaker up --image my-llmaker
`
